### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by steved1982** [Swader/diffbot-php-client#24]
I have installed diffbot using composer and it created the autoload files as normal.

My code is simply:

require_once "../../vendor/autoload.php";
$diffbot = new Diffbot('KEY');

BUT I get the error:
PHP Fatal error:  Class 'Diffbot' not found 

I am running PHP Version 5.6.12

**Comment by Swader** [comment]
Use the fully qualified class name:

```php
$diffbot = new Swader\Diffbot\Diffbot('KEY');
```

or import it at the top and then use the short form:

```php
use Swader\Diffbot\Diffbot;

$diffbot = new Diffbot('KEY');
```

**Comment by steved1982** [comment]
Thank you!
