### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '.' in vendor/swader/diffbot-php-client/src/Entity/EntityIterator.php on line 87

### ISSUE THREAD

**Issue by ankushdharkar** [Swader/diffbot-php-client#28]
PHP Parse error:  syntax error, unexpected '.' in vendor/swader/diffbot-php-client/src/Entity/EntityIterator.php on line 87

```php
$rv = $zeroth->$name(...$args);
```

**Comment by Swader** [comment]
As the README states, you need PHP 5.6 to use this library.

The error above is due to an outdated PHP version which does not support argument unpacking (`...`).

**Comment by ankushdharkar** [comment]
@Swader : Thanks.
