### ISSUE TITLE
composer require swader/diffbot-php-client fails

### ISSUE THREAD

**Issue by jonathantullett** [Swader/diffbot-php-client#38]
I'm trying to do the recommended installation method for this library but it's failing:

```
$ composer require swader/diffbot-php-client
Using version ^1.2 for swader/diffbot-php-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - swader/diffbot-php-client 1.2.1 requires php-http/utils dev-master -> satisfiable by php-http/utils[dev-master].
    - php-http/utils dev-master requires php-http/httplug 1.0.0-beta -> satisfiable by php-http/httplug[v1.0.0-beta].
    - Conclusion: don't install php-http/httplug v1.0.0-beta
    - Can only install one of: php-http/httplug[v1.0.0-alpha3, v1.0.0].
    - Can only install one of: php-http/httplug[v1.0.0-alpha3, v1.0.0].
    - Can only install one of: php-http/httplug[v1.0.0-alpha3, v1.0.0].
    - php-http/utils v0.1.0 requires php-http/httplug 1.0.0-alpha3 -> satisfiable by php-http/httplug[v1.0.0-alpha3].
    - swader/diffbot-php-client 1.2 requires php-http/utils ^0.1.0@dev -> satisfiable by php-http/utils[v0.1.0].
    - Installation request for swader/diffbot-php-client ^1.2 -> satisfiable by swader/diffbot-php-client[1.2, 1.2.1].
    - Installation request for php-http/httplug == 1.0.0.0 -> satisfiable by php-http/httplug[v1.0.0].
```

What's the recommended course of action here?  My 'minimum-requirements' are 'dev'.

Thanks very much.

**Comment by Swader** [comment]
Will be fixed tomorrow, there has been a critical development IRT dependencies, very sorry about this, working on it!

**Comment by Swader** [comment]
Hey @jonathantullett sorry about the delay, significant updates had to be made and I have just released version 2.0.

No API changes, so it's all the same towards the front, but the dependencies have changes a lot so this required a major version shift. Please try it out and let me know if it's okay now.

Remember to set both minimum-stability to dev, and prefer-stable to true for best effects, and install an HTTP client before you start using the package and installing other dependencies, for example with `composer require php-http/guzzle6-adapter`.

**Comment by jonathantullett** [comment]
I've got it all working now. Thanks for your time and effort to fix the breakage :)

**Comment by Swader** [comment]
Good to hear, enjoy! :)

Oh btw, if you need inspiration: [Diffbot archives](http://www.sitepoint.com/tag/diffbot/)
