### ISSUE TITLE
Questions about the right way to get subarray like images/tags

### ISSUE THREAD

**Issue by realwindz** [Swader/diffbot-php-client#40]
Hi, I`m using the php library. Normally I use the field array as:

```php
 $fields = array("author", "title", "siteName", "date", "icon", "images","html","tags"); // fields to be returned
 $json_diffr = $d->article($myurl, $fields);
```

But the returned json didn`t contain the scores or url as the website shown. 
I tried to use like this 

```php
$tag=array("scores","labels","url");
$fields=array("author","title",$tag);
```

but the json still not returning the scores for tags.

**Comment by Swader** [comment]
Hi,

which PHP client are you using? With this one (the one in whose repo you're in right now) it's as simple as:

```php
$d = new Diffbot('mytoken');
$result = $d->createArticleAPI('http://www.cnn.com/2016/03/03/middleeast/syria-war/')->call();

$tags = $result->getTags();
```

No need for fields or anything else.

**Comment by realwindz** [comment]
OK, cool, seems like you updated the API. I was using this one:
https://github.com/diffbot/diffbot-php-client

Maybe you can redirect your PHP library to this new one API

**Comment by Swader** [comment]
Ah, yes, forgot about that - I've put up a deprecation notice and will do a full redirect soon.
