### ISSUE TITLE
Problem installing guzzle6-adapter

### ISSUE THREAD

**Issue by karam89** [Swader/diffbot-php-client#48]
Dear diffbot community:

I'm trying to install diffbot using composer,
1- Downloaded the latest version (2.0.1)
2- Rechecked the lines 
    "prefer-stable": true,
    "minimum-stability": "dev"
in the composer.json

3- Executed the following
composer require php-http/guzzle6-adapter

Every thing seems to be ok until I get the following at the end of the installation
**Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.**
**Warning: Version check failed: Could not determine Puli version. "puli -V" returned:**

(Tried minimum-stability as dev, beta, stable >>> not resolved)

So that I can't install diffbot-php-client

**Comment by Swader** [comment]
Looking into it, will have more info soon.

**Comment by Swader** [comment]
Please try again now, it should be cleared up. Here's a sample `composer.json` for reference:

```json
{
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php-http/guzzle6-adapter": "~1.0",
        "php-http/message": "^1.2",
        "php-http/discovery": "~0.8.0",
        "puli/cli": "~1.0",
        "php-http/plugins": "~1.0",
        "puli/composer-plugin":"^1.0",
        "swader/diffbot-php-client": "^2.1@dev"
    }
}

```
