### ISSUE TITLE
Number of results to return from search API

### ISSUE THREAD

**Issue by felixbridell** [Swader/diffbot-php-client#55]
Hi.
I'm trying to use the search api to get all results from a crawl robot. In diffbots documentation I see that it's possible to use the num option (num=all) but how do I do that using the diffbot-php-client? I tried:
`$search = $diffbot->search('type:product AND num:all')->setCol($crawlName)->call();`
and
`$search = $diffbot->search('type:product')->setCol($crawlName)->num('all')->call();`
but no luck.

**Comment by Swader** [comment]
As per [the docs](http://diffbot-php-client-docs.readthedocs.io/en/latest/api-search.html#setnum), use `setNum`.
